In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)


[ 2  6 12 20]


reshape() ile boyutu değişiyo

In [4]:


x=np.array([1,2,3,4,5,6,7,8,9])

multi=x.reshape(3,3)

print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape() ile boyutları öğreniliyo

In [5]:
print(multi.shape)

(3, 3)


.ndim ile arraylerin boyut sayısı öğrenilir

In [6]:
print(x.ndim)

1


In [7]:
print(multi.ndim)

2


.concatenate() ile birleştirilir

In [8]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])

print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a=np.array([[1,2,3],[4,5,6]])

print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis=0 satır bazında birleştirme yapar
axis=1 sütun bazında birleştirme yapar

In [11]:
print(np.concatenate([a,a],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


.split() array ayırır

In [12]:
m=np.array([1,2,3,99,99,3,2,1])

print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [13]:
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


.vsplit() fonksiyonu ile yatay olaray ayırma yapılabilir
.hsplit() fonksiyonu ile diket olarak ayırma yapılabilir

In [14]:
n=np.arrange(16).reshape(4,4)
np.vsplit(n,[2])

AttributeError: module 'numpy' has no attribute 'arrange'

In [15]:
np.hsplit(n,[2])

NameError: name 'n' is not defined

np.zeros () o lardan olusan numpy dizisi verir

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

np.arrange()
belirli aralıkta sayıları oluşturmak için kullanılır
np.arrange(start,stop,step)

In [16]:
np.arrange(3,12,2)

AttributeError: module 'numpy' has no attribute 'arrange'

np.ones()
1 lerden olusan dizi verir

In [18]:
np.ones(55)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

np.linspace(başlangıc,bitiş,bölünecel aralık) belirli aralıktaki sayı dizisini oluşturmak için kullanılır

In [22]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

rastegele aralıkta değişkenler olusturmak ıcın

In [23]:
np.random.randint(0,10,3)

array([8, 3, 9])

In [24]:
npArray=np.arrange(50)
npMulti=npArray.reshape(5,10)
print(npMulti.sum(axis=1))


AttributeError: module 'numpy' has no attribute 'arrange'

numpy ve arrayin ortak özellikleri
ndim:boyut sayııs
shape:boyut bilgisi
size:toplam eleman
dtype:veri tipi

In [25]:
a=np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


arrayler sort() fonksiyonu ile sıralanır

In [30]:
v=np.array([1,2,5,10,11,232,42,55])
print(v)
v.sort()
print(v)


[  1   2   5  10  11 232  42  55]
[  1   2   5  10  11  42  55 232]


index ile elemanlara erişebiliriz

In [32]:
a=np.random.randint(10,size=10)
print(a[0])

1


In [33]:
a[0]=100
print(a)

[100   7   1   5   6   5   9   8   9   3]


In [35]:
a=np.random.randint(10,size=(3,5))
print(a)

[[7 3 4 4 8]
 [5 8 2 7 8]
 [6 5 7 1 9]]


In [36]:
print(a[0,0])

7


In [37]:
print(a[1,1])

8


In [39]:
a[1,4]=100
print(a)

[[  7   3   4   4   8]
 [  5   8   2   7 100]
 [  6   5   7   1   9]]


slicing ile array alt kümesine erişmek

In [40]:
a=np.arrange(20,30)
print(a)

AttributeError: module 'numpy' has no attribute 'arrange'

In [2]:
pip install numpy

     ---------------------------------------- 14.8/14.8 MB 2.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip
