# Problem 1 

In [2]:
import numpy as np

dizi= np.array([55,7,4,99,15])


diziSıra = np.sort(dizi)

print(diziSıra)



[ 4  7 15 55 99]


# Problem 2

In [3]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

import numpy as np

dizi = np.array([10, 15, 30, 45, 60])


# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

dizi2 = np.arange(5, 16)

 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

dizi3 = np.arange(50, 101, 5)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

dizi4 = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

dizi5 = np.ones(10)


# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

dizi6 = np.linspace(0, 100, 5)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

dizi7 = np.random.randint(10, 31, 5)



# 8- [-1 ile 1] arasında 10 adet sayı üretin.

dizi8 = np.random.uniform(-1, 1, 10)


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

dizi9 = np.random.randint(10, 51, (3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

print("Satır toplamları:", np.sum(dizi9, axis=1))
print("Sütun toplamları:", np.sum(dizi9, axis=0))


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

print("En büyük değer:", np.max(dizi9))
print("En küçük değer:", np.min(dizi9))
print("Ortalama değer:", np.mean(dizi9))


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

max_index = np.argmax(dizi9)
print("En büyük değerin indeksi:", max_index)



# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

dizi13 = np.arange(10, 21)
print("İlk 3 eleman:", dizi13[:3])



# 14- Üretilen dizinin elemanlarını tersten yazdırın.

print("Tersten yazdırılmış dizi:", dizi13[::-1])



# 15- Üretilen matrisin ilk satırını seçiniz.

print("İlk satır:", dizi9[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print("2. satır, 3. sütundaki eleman:", dizi9[1, 2])



# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print("Tüm satırlardaki ilk elemanlar:", dizi9[:, 0])


# 18- Üretilen matrisin her bir elemanının karesini alınız.
print("Kareleri alınmış matris:")
print(np.square(dizi9))


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

pozitif = dizi9[(dizi9 > 0) & (dizi9 % 2 == 0)]
print("Pozitif çift sayılar:", pozitif)


Satır toplamları: [156 120 185]
Sütun toplamları: [ 99  90  84 115  73]
En büyük değer: 50
En küçük değer: 14
Ortalama değer: 30.733333333333334
En büyük değerin indeksi: 13
İlk 3 eleman: [10 11 12]
Tersten yazdırılmış dizi: [20 19 18 17 16 15 14 13 12 11 10]
İlk satır: [35 17 34 40 30]
2. satır, 3. sütundaki eleman: 24
Tüm satırlardaki ilk elemanlar: [35 27 37]
Kareleri alınmış matris:
[[1225  289 1156 1600  900]
 [ 729  900  576  625  196]
 [1369 1849  676 2500  841]]
Pozitif çift sayılar: [34 40 30 30 24 14 26 50]
